Feat/observability support
NVIDIA/NeMo-Guardrails pull request #798
Opened 2024-10-10 13:42 UTC by Pouyanpi

## Description
Implements a tracing module to assign a trace id to every incoming request and enable detailed tracing of every rail/action/LLM call that is triggered behind the scenes. Can export the traces to different providers like OpenTelemetry, etc.
## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/CONTRIBUTING.md) guidelines.
- [ ] I've updated the documentation if applicable.
- [ ] I've added tests if applicable.

2024-10-11 12:54 UTC, drazvan requested changes
Looks good :+1:. After fixing the issues, good to merge.

2024-10-11 12:54 UTC, drazvan commented on nemoguardrails/rails/llm/config.py
> +class AdapterConfig(BaseModel):
Maybe rename to `LogAdapterConfig`

2024-10-11 12:54 UTC, drazvan commented on nemoguardrails/rails/llm/llmrails.py
> +                tracer.export()
This seems blocking.

2024-10-11 12:54 UTC, drazvan commented on nemoguardrails/tracing/adapters/filesystem.py
> +            self.filepath = "./.traces/trace.json"
This should be .jsonl.

2024-10-11 12:54 UTC, drazvan commented on nemoguardrails/rails/llm/llmrails.py
> +                tracer = Tracer(
To check if this initializes OTEL every time or not.

2024-10-16 09:12 UTC, Pouyanpi commented
@drazvan the changes are done. Currently tracing dependencies are added to `pyproject.toml` and using defered import like similar situations in the codebase would clutter the `adapters.opentelmetry` module. Dependency req is included in the documentation.

2024-10-18 13:20 UTC, drazvan approved these changes
Approving to unblock. Will review in more detail next week.

2024-10-18 14:06 UTC, merged