feat: add pii masking capability to private ai integration
NVIDIA/NeMo-Guardrails pull request #901
Opened 2024-12-11 17:16 UTC by letmerecall

## Description

This PR enhances [Private AI](docs.private-ai.com) integration by adding support for PII masking capabilities. Previously, Private AI integration allowed for PII detection, preventing texts containing PII from being sent to the LLM or end user. With the new masking feature, texts can now be sanitized and shared with the LLM or user in a masked format.

For example, given the user input:
```
My email id is user@email.com
```

The PII masking configuration can transform the text into:
```
My email id is [EMAIL]
```
This enables safe data handling while maintaining the contextual integrity of the input.

@Pouyanpi 

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/CONTRIBUTING.md) guidelines.
- [x] I've updated the documentation if applicable.
- [x] I've added tests if applicable.
- [x] @mentions of the person or team responsible for reviewing proposed changes.

2025-01-08 08:58 UTC, letmerecall commented
@Pouyanpi hope you had a wonderful holidays. PTAL whenever you find some time.

2025-01-09 10:10 UTC, Pouyanpi commented on docs/user-guides/guardrails-library.md
> +NeMo Guardrails supports using [Private AI API](https://docs.private-ai.com/?utm_medium=github&utm_campaign=nemo-guardrails) for PII detection and masking the in input, output and retrieval flows.
```suggestion
NeMo Guardrails supports using [Private AI API](https://docs.private-ai.com/?utm_medium=github&utm_campaign=nemo-guardrails) for PII detection and masking input, output and retrieval flows.
```

2025-01-09 10:18 UTC, Pouyanpi commented on nemoguardrails/library/privateai/actions.py
> +    """
```suggestion
    """Masks any detected PII in the provided text.

    Args:
        source (str): The source for the text, i.e. "input", "output", "retrieval".
        text (str): The text to check.
        config (RailsConfig): The rails configuration object.

    Returns:
        str: The altered text with PII masked.
    """

```

2025-01-09 10:24 UTC, Pouyanpi commented on nemoguardrails/library/privateai/request.py
>      """
```suggestion
    """Send a PII detection request to the Private AI API.
    
```

2025-01-09 10:24 UTC, Pouyanpi commented on nemoguardrails/library/privateai/request.py
> +    Send a PII detection request to the Private AI API.
```suggestion
```

2025-01-09 10:28 UTC, Pouyanpi commented on nemoguardrails/library/privateai/request.py
> +            return await resp.json()
improve error handling for response parsing

As a suggestion, but please decide for yourself I have not given it much thought
```
            try:
                response_json = await resp.json()
            except aiohttp.ContentTypeError:
                raise ValueError(
                    f"Failed to parse response as JSON. Status: {resp.status}, "
                    f"Content: {await resp.text()}"
                )
```

2025-01-09 10:29 UTC, Pouyanpi commented on nemoguardrails/library/privateai/actions.py
> +    return private_ai_response[0]["processed_text"]
- Ensure that `private_ai_response[0]["processed_text"]` is always valid to avoid potential index errors. 
- Improve error handling
- Update docstring with Raises (see [ref](https://google.github.io/styleguide/pyguide.html#doc-function-raises))

2025-01-09 10:38 UTC, Pouyanpi requested changes
Thank you @letmerecall for the PR, please review my comments.

current tests for PII detection and masking are using mocked responses. While this is great for unit testing, it doesn't really test the actual integration with the Private AI API. I think we should consider adding some integration tests using temporary credentials to make sure everything works end-to-end. What do you think about it @letmerecall? I am not quite sure wether the mock requests and response accurately mocks Private AI API.

Also, let's make sure our tests cover error scenarios, like what happens if the API key is missing or invalid. This will help us catch any potential issues early

2025-01-09 20:01 UTC, letmerecall commented
> Thank you @letmerecall for the PR, please review my comments.
> 
> current tests for PII detection and masking are using mocked responses. While this is great for unit testing, it doesn't really test the actual integration with the Private AI API. I think we should consider adding some integration tests using temporary credentials to make sure everything works end-to-end. What do you think about it @letmerecall? I am not quite sure wether the mock requests and response accurately mocks Private AI API. You can have a look at this [sensitive content detection tests](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/tests/test_sensitive_data_detection.py) or its refinement in #845
> 
> Also, let's make sure our tests cover error scenarios, like what happens if the API key is missing or invalid. This will help us catch any potential issues early

Having a temp Private AI API key to test is a good idea. Let me get back to you on that.

Thanks for the review and the references. I'll address them soon :)

2025-01-20 17:36 UTC, letmerecall commented on nemoguardrails/library/privateai/request.py
> +            return await resp.json()
This sounds just right. Other issues should be be captured by status check above.

2025-01-20 18:00 UTC, letmerecall commented
Hey @Pouyanpi, added error handling and live api testing.

Will it be possible for you to generate an API key using our portal? https://portal.private-ai.com? We can then bake it in as a secret for github actions. If you decide to do it, let me know your email id after creating a key, we can increase the quota accordingly :)

2025-01-21 08:09 UTC, Pouyanpi approved these changes
Thank you @letmerecall 👍🏻

2025-01-21 08:10 UTC, merged